package java_new_features.java_4_and_5_features;
enum EnumExample3 
{
   	WINTER(10),SUMMER(20); 
   	private int value;
   	EnumExample3(int value)
   	{
   		this.value=value;
   	}
}	

/* Internal Code generated by the compiler
final class EnumExample3 extends Enum  
{  
    public static EnumExample3[] values()  
    {  
        return (EnumExample3[])$VALUES.clone();  
    }  
    public static EnumExample3 valueOf(String s)  
    {  
        return (EnumExample3)Enum.valueOf(EnumExample3, s);  
    }  
    private EnumExample3(String s, int i, int j)  
    {  
        super(s, i);  
        value = j;  
    }  
    public static final EnumExample3 WINTER;  
    public static final EnumExample3 SUMMER;  
    private int value;  
    private static final EnumExample3 $VALUES[];  
    static   
    {  
        WINTER = new EnumExample3("WINTER", 0, 10);  
        SUMMER = new EnumExample3("SUMMER", 1, 20);  
        $VALUES = (new EnumExample3[] {  
            WINTER, SUMMER  
        });  
    }  
}    
*/
 