package java_new_features.java_4_and_5_features;
public class EnumExample1
{
	public enum Season 
	{
		WINTER,SPRING,SUMMER,FALL
	}
	public static void main(String args[])
	{
		for(Season s:Season.values())
		{
			System.out.println(s);
		}
	}
}
/* Internal Code Generated by the compiler
public static final class EnumExample1$Season extends Enum  
{  
  private EnumExample1$Season(String s, int i)  
    {  
        super(s, i);  
    }  
  
    public static EnumExample1$Season[] values()  
    {  
        return (EnumExample1$Season[])$VALUES.clone();  
    }  
  
    public static EnumExample1$Season valueOf(String s)  
    {  
        return (EnumExample1$Season)Enum.valueOf(EnumExample1$Season, s);  
    }  
  
    public static final EnumExample1$Season WINTER;  
    public static final EnumExample1$Season SPRING;  
    public static final EnumExample1$Season SUMMER;  
    public static final EnumExample1$Season FALL;  
    private static final EnumExample1$Season $VALUES[];  
  
    static   
    {  
        WINTER = new EnumExample1$Season("WINTER", 0);  
        SPRING = new EnumExample1$Season("SPRING", 1);  
        SUMMER = new EnumExample1$Season("SUMMER", 2);  
        FALL = new EnumExample1$Season("FALL", 3);  
        $VALUES = (new EnumExample1$Season[] {  
            WINTER, SPRING, SUMMER, FALL  
        });  
    }    
}  
*/